# Generated by Django 5.0.1 on 2024-06-29 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
